# Site settings
title: Matheus Godoy
email: matheusgodoy@me.com
description: >-
  Esse é o meu blog, meu objetivo é compartilhar com meus filhos o que deu certo e errado na minha busca por liberdade.
baseurl: ""
url: ""

# Social
twitter_username: matheusdotlat
github_username: matheus

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
