# Site settings
title:          Matheus
description:    "Em busca de liberdade"
baseurl:        "/"
url:            "https://matheus.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Matheus
  url:          https://linktr.ee/matheusgodoy
  email:        matheusgodoy@me.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale